### PR TITLE
fix(passport): scope description on hover in authorisation screen

### LINKED ISSUE #2039: bug(passport): Information tooltip doesn't display for scope values in authz screen
When the authorization screen is presented, the information icon (round icon with `i` in it) does not pop up with a tooltip containing the description of the scope value.

### PR DESCRIPTION
**Pull request by poolsar42**
# Description

Returns a tooltip which provides scope description in Authorisation screen

- Closes #2039

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Visual changes were tested by starring at the component hovering cursor back and forth

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation website
- [ ] I have made corresponding changes to the literal docs
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: apps/passport/app/components/authorization/Info.tsx [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+  description,
+}: {
+  name: string
+  description: string
+}) {
+  return (
+    <Tooltip
+      content={description}
+      className="bg-white text-black shadow-xl absolute z-5"
+      placement={name === 'Email' ? 'bottom' : 'right'}
```
Comment (maurerbot) [inline apps/passport/app/components/authorization/Info.tsx:15]: not sure it's a good idea to hardcode scope placements inside a generic component. placement should be decided externally

**Review by maurerbot — CHANGES_REQUESTED** [review]

**Review by maurerbot — CHANGES_REQUESTED** [review]
- shouldn't be bold
- should work on mobile
- should work on hover and click

image

**Review by maurerbot — APPROVED** [review]
