### PR TITLE
fix(passport): displaying app's favicon in custom domain

### LINKED ISSUE #2392: chore(passport): apply designer colors to loading bar

### LINKED ISSUE #2406: fix(passport): Rollup's favicon still displayed on the MetaMask Notification window post enabling custom domain and white labelling
### Description
Rollup's favicon still displayed on the MetaMask Notification window post enabling custom domain and white labelling

### Pre-requisite
Enable custom domain and white labelling

### Steps to Reproduce
1. Goto https://ppe-auth.plnetwork.io/ (a custom domain registered with rollup)
2. Select the option 'Connect with Wallet'
3. Select 'MetaMask' in the Connect Wallet-pop up
4. Select 'Connect' and 'Sign' in the following pop ups.

### Expected Behavior
Rollup's favicon should not be displayed - since custom domain and white labelling are enabled

### Actual Behavior
Rollup's favicon is still displayed even after custom domain and white labelling are enabled

### Screenshots
image

### PR DESCRIPTION
**Pull request by poolsar42**
### Description

App's favicon on now displayed on the MetaMask Notification window

Loader in passport now reflects colours that were set in designer for specific app

Fixes bugs with redirects in passport which were not indicated in any other issues, stable temporary solution for `/sign` route when there's an error occurs. Solves issue with `/authenticate` route to not redirect to `/settings/dashboard` logged-in users.

Fetches appProps from starbase before loading context and puts it in the context object.

### Related Issues

- Closes #2406
- Closes #2392 

### Testing

Go to authn screen and pop-up metamask window to sign a message. Under custom domain or just with clientId for the specific app.

### Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) guidelines
- [x] I have tested my code (manually and/or automated if applicable)
- [ ] I have updated the documentation (if necessary)

### CODE REVIEW

File: apps/passport/app/root.tsx [hunk 1]
```diff
@@ -90,6 +93,25 @@ export const loader: LoaderFunction = getRollupReqFunctionErrorWrapper(
       return redirect(`/authenticate`)
     }
 
+    let appProps: GetAppPublicPropsResult
```
Comment (maurerbot) [inline apps/passport/app/root.tsx:96]: is this not already in context?

**Review by maurerbot — CHANGES_REQUESTED** [review]

File: apps/passport/app/root.tsx (hunk 1 above)
Comment (poolsar42) [reply apps/passport/app/root.tsx:96]: @maurerbot  nope
```ts
{
  context: {
    authzQueryParams: {
      clientId: '',
      state: '',
      redirectUri: '',
      scope: [],
      prompt: undefined,
      login_hint: undefined,
      rollup_action: undefined,
      rollup_result: undefined
    },
    env: ServiceWorkerGlobalScope {},
    traceSpan: TraceSpan {
      traceId: '70c7e789dfcd23ea82eecac91c7aaf53',
      spanId: 'a0c0d5b6de5115dd',
      startTime: 1686932216223
    }
  }
}
```

Comment (maurerbot) [reply apps/passport/app/root.tsx:96]: we must be checking for custom domain somewhere and pulling in appdata?

**Comment by szkl** [comment]
The commit message should be about the changes in the pull request.

File: apps/passport/app/root.tsx (hunk 1 above)
Comment (poolsar42) [reply apps/passport/app/root.tsx:84]: All things wee need to fetch appData is clientId. In custom domains it is being provided if I recall correctly and we tested its validity for custom domain with @szkl recently

Comment (poolsar42) [reply apps/passport/app/root.tsx:84]: [Here's](https://github.com/proofzero/rollupid/pull/2418/files#diff-82fd3722cfe289403dc38fada2d909c4ce54846ad0bfa9b0693f9500c35d341bR86) the check for clientId

Comment (poolsar42) [reply apps/passport/app/root.tsx:84]: Haha its done actually take a look [here](https://github.com/proofzero/rollupid/pull/2418/files#diff-82fd3722cfe289403dc38fada2d909c4ce54846ad0bfa9b0693f9500c35d341bR86)

File: apps/passport/app/root.tsx [hunk 2]
```diff
@@ -78,6 +81,32 @@ export const links: LinksFunction = () => [
 
 export const loader: LoaderFunction = getRollupReqFunctionErrorWrapper(
   async ({ request, context, params }) => {
+    let appProps: GetAppPublicPropsResult
+
+    if (context?.authzQueryParams?.app_props) {
```
Comment (maurerbot) [inline apps/passport/app/root.tsx:86]: can't we assume it will always be there? if it's not it is probably console or passport?

File: apps/passport/server.ts [hunk 3]
```diff
@@ -90,6 +95,7 @@ const handleEvent = async (event: FetchEvent) => {
 
     try {
       const app = await starbaseClient.getAppPublicProps.query({ clientId })
```
Comment (maurerbot) [inline apps/passport/server.ts:97]: why not skip if passport or console?

Comment (szkl) [reply apps/passport/server.ts:93]: Line 84 checks for a custom domain request. If it is a custom domain request then there's a clientId.

**Review by szkl — APPROVED** [review]
