### PR TITLE
fix(console): Remove reference edges before removing app node

### LINKED ISSUE #2480: fix(edges): deleting published app in console causes edges error
### Description

When published app in console is deleted, user is being redirected to `/apps/delete` and getting stuck there.

### Steps to Reproduce

1. Publish app in console
2. Delete it without unpublishing

### Expected Behavior

User should be able to delete app without errors.

### Actual Behavior

Here're the logs from starbase: 
```ts
➤ YN0000: [@proofzero/platform.starbase]: TRPCClientError: D1_ERROR
➤ YN0000: [@proofzero/platform.starbase]:     at TRPCClientError.from (index.js:11546:14)
➤ YN0000: [@proofzero/platform.starbase]:     at index.js:11931:44 {
➤ YN0000: [@proofzero/platform.starbase]:   code: INTERNAL_SERVER_ERROR,
➤ YN0000: [@proofzero/platform.starbase]:   name: TRPCError,
➤ YN0000: [@proofzero/platform.starbase]:   stack: TRPCClientError: D1_ERROR
➤ YN0000: [@proofzero/platform.starbase]:     at TRPCClientError.from (index.js:11546:14)
➤ YN0000: [@proofzero/platform.starbase]:     at index.js:11931:44,
➤ YN0000: [@proofzero/platform.starbase]:   message: D1_ERROR,
```

Here're the logs from edges:
```ts
Error: D1_ERROR
➤ YN0000: [@proofzero/platform.edges]:     at D1Database._send (index.js:10379:13)
➤ YN0000: [@proofzero/platform.edges]:     at async D1Database.batch (index.js:10325:18)
➤ YN0000: [@proofzero/platform.edges]:     at async deleteNodeMethod (index.js:10261:19)
➤ YN0000: [@proofzero/platform.edges]:     at async resolveMiddleware (index.js:6892:22)
➤ YN0000: [@proofzero/platform.edges]:     at async callRecursive (index.js:6925:25)
➤ YN0000: [@proofzero/platform.edges]:     at async next (index.js:6933:20)
➤ YN0000: [@proofzero/platform.edges]:     at async outputMiddleware (index.js:6789:20)
➤ YN0000: [@proofzero/platform.edges]:     at async callRecursive (index.js:6925:25)
➤ YN0000: [@proofzero/platform.edges]:     at async next (index.js:6933:20)
➤ YN0000: [@proofzero/platform.edges]:     at async callRecursive (index.js:6925:25) {
➤ YN0000: [@proofzero/platform.edges]:   code: INTERNAL_SERVER_ERROR,
➤ YN0000: [@proofzero/platform.edges]:   name: TRPCError,
➤ YN0000: [@proofzero/platform.edges]:   stack: Error: D1_ERROR
➤ YN0000: [@proofzero/platform.edges]:     at D1Database._send (index.js:…20)
➤ YN0000: [@proofzero/platform.edges]:     at async callRecursive (index.js:6925:25),
➤ YN0000: [@proofzero/platform.edges]:   message: D1_ERROR,
```

### PR DESCRIPTION
**Pull request by betimshahini**
### Description

`deleteApp()` was removing the app edge, but was not also removing the edge references that are used to associate the dev email to the app. This fixes the scenario.

### Related Issues

- Closes #2480

### Testing

1. Create app in Console
2. Associate a dev email in Team and Contacts
3. Go back to dashboard and delete app. 

### Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) guidelines
- [x] I have tested my code (manually and/or automated if applicable)
- [ ] I have updated the documentation (if necessary)

### CODE REVIEW

**Review by maurerbot — APPROVED** [review]

File: platform/starbase/src/jsonrpc/methods/deleteApp.ts [hunk 1]
```diff
@@ -36,11 +37,28 @@ export const deleteApp = async ({
...
+      })
+    ),
+    //Application edge
+    caller.edges.removeEdge({
+      src: ctx.accountURN,
+      dst: appURN,
+      tag: EDGE_APPLICATION,
+    }),
+  ]
+  await Promise.all(edgeRemovalPromises)
```
Comment (maurerbot) [inline platform/starbase/src/jsonrpc/methods/deleteApp.ts:60]: Promise.all does only await multiple promises. It doesn't care in what order they resolve, or whether the computations are running in parallel.

**Review by maurerbot — CHANGES_REQUESTED** [review]
should just be two awaits in sequence?

**Review by maurerbot — APPROVED** [review]
