### PR TITLE
fix(profile): og images

### LINKED ISSUE #1721: fix(profile): cover photo not rendering in og tag
Image

### LINKED ISSUE #1724: chore(apps): audit og tags to be consistent with messaging.
e.g. og tags on passport still say simple & secure onboarding

### LINKED ISSUE #1728: chore(profile): og tag taking a long time to generate
- [ ] investigate how we can make this faster

### PR DESCRIPTION
**Pull request by poolsar42**
# Description

Optimization and fixing og image generation for profile.

- Closes #1721
- Closes #1728
- Closes #1724

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation website
- [ ] I have made corresponding changes to the literal docs
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: packages/platform-clients/image.ts [hunk 1]
```diff
@@ -1,15 +1,22 @@
...
   createTRPCProxyClient<Router.ImageRouter>({
     links: [
       httpBatchLink({
         url: 'http://localhost/trpc',
-        fetch: fetcher.fetch.bind(fetcher), // NOTE: preflight middleware?
-        headers() {
-          return headers || {}
-        },
+        fetch: (input, init?: RequestInit<RequestInitCfProperties>) => {
+          defaultsDeep(init, options)
```
[the remark this answers is not in the document]
Comment (maurerbot) [reply packages/platform-clients/image.ts:17]: or

```js
const newInit = {...init, cf: {...init.cf, ...cf} }
```

maybe add a check for init.cf

**Review by maurerbot — CHANGES_REQUESTED** [review]

File: packages/platform-clients/package.json [hunk 2]
```diff
@@ -35,6 +35,7 @@
     "typescript": "4.8.4"
   },
   "dependencies": {
-    "@trpc/client": "10.8.1"
+    "@trpc/client": "10.8.1",
+    "lodash": "4.17.21"
```
Comment (maurerbot) [inline packages/platform-clients/package.json:39]: delete

File: platform/images/src/jsonrpc/methods/getOgImage.ts [hunk 3]
```diff
@@ -95,47 +97,48 @@ export const getOgImageMethod = async ({
...
-        success: boolean
-        result: { variants: string[] }
-        errors: any
-      }>()
-    )
-    .catch((e) => {
-      console.error("Couldn't upload og image to CF")
-      console.error(e)
+
+  const direct_upload = await uploadRequest.json<{
```
Comment (maurerbot) [inline platform/images/src/jsonrpc/methods/getOgImage.ts:110]: revert. you shuold get a 409 and it will work

**Review by maurerbot — CHANGES_REQUESTED** [review]

File: apps/passport/app/utils/authenticate.server.ts [hunk 4]
```diff
@@ -87,6 +87,12 @@ const provisionProfile = async (jwt: string, env: Env, address: AddressURN) => {
   if (!profile) {
     console.log(`Profile doesn't exist for account ${account}. Creating one...`)
     const addressClient = getAddressClient(address, env)
+    /**
+     * Hardcoded url for default cover image
+     * to not upload it every time on each new user
+     */
+    const cover =
```
[the remark this answers is not in the document]
Comment (poolsar42) [reply apps/passport/app/utils/authenticate.server.ts:94]: nope, here it should be image url, because it's a part of newly created profile

**Comment by poolsar42** [comment]
- [ ] put domains in wrangler
- [ ] env variables for url in images client
- [ ] delete cf header and do caching in images worker side
- [ ] update cache storage for updateOgImage
- [ ] delete cache when updating profile

File: packages/platform-clients/image.ts [hunk 5]
```diff
@@ -1,15 +1,24 @@
 import { createTRPCProxyClient, httpBatchLink } from '@trpc/client'
 import { Router } from '@kubelt/types'
 
-export default (fetcher: Fetcher, headers?: Record<string, string>) =>
+export default (
+  fetcher: Fetcher,
+  imagesURL: string,
+  options?: {
+    cf?: RequestInitCfProperties
```
Comment (maurerbot) [inline packages/platform-clients/image.ts:8]: make `imagesURL` optional field in options

File: packages/platform-clients/image.ts [hunk 6]
```diff
@@ -1,15 +1,24 @@
...
+) =>
   createTRPCProxyClient<Router.ImageRouter>({
     links: [
       httpBatchLink({
-        url: 'http://localhost/trpc',
-        fetch: fetcher.fetch.bind(fetcher), // NOTE: preflight middleware?
-        headers() {
-          return headers || {}
-        },
+        url: imagesURL,
```
Comment (maurerbot) [inline packages/platform-clients/image.ts:15]: make this a tenrary and use localhost if not set. this means you can get rid of imagesURL in all the other apps and use it in profile only.

**Review by maurerbot — CHANGES_REQUESTED** [review]

File: packages/platform-clients/image.ts [hunk 7]
```diff
@@ -2,18 +2,27 @@ import { createTRPCProxyClient, httpBatchLink, loggerLink } from '@trpc/client'
...
       httpBatchLink({
-        url: 'http://localhost/trpc',
-        fetch: fetcher.fetch.bind(fetcher), // NOTE: preflight middleware?
-        headers() {
-          return headers || {}
-        },
+        url: options?.imagesURL || 'http://localhost/trpc',
+        fetch: (input, init?: RequestInit<RequestInitCfProperties>) => {
+          if (init && options?.cf) {
+            init.cf = options.cf
```
Comment (maurerbot) [inline packages/platform-clients/image.ts:22]: rever this whole thing

File: platform/images/src/jsonrpc/methods/getOgImage.ts [hunk 8]
```diff
@@ -3,9 +3,10 @@ import { z } from 'zod'
 import wasm from '../../assets/svg2png_wasm_bg.wasm'
 import { svg2png, initialize } from 'svg2png-wasm'
 import { Context } from '../../context'
+//@ts-ignore
```
Comment (maurerbot) [inline platform/images/src/jsonrpc/methods/getOgImage.ts:6]: drop ts ignore

File: platform/images/src/jsonrpc/methods/getOgImage.ts [hunk 9]
```diff
@@ -20,7 +21,14 @@ export const getOgImageMethod = async ({
   input: getOgImageParams
   ctx: Context
 }): Promise<getOgImageOutputParams> => {
-  const { bgUrl, fgUrl } = input
+  const cache = await caches.open('rollup:ogimage')
+  const cachedRes = await cache.match(ctx.req!)
+  if (cachedRes) {
+    console.log({ status: cachedRes.status })
```
Comment (maurerbot) [inline platform/images/src/jsonrpc/methods/getOgImage.ts:27]: change to console debug

**Review by maurerbot — CHANGES_REQUESTED** [review]

**Review by maurerbot — APPROVED** [review]
